name: Deploy

env:
  APP_LOCATION: "build" # location of client code build output

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - name: Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.deployment_token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_app_build: true
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
